vhost: fix compile fail due to reallocated acked_features field.
The cherry pick of commit ea16c51433510f7f758382dec5b933fc0797f244
("vhost: move acked_features to VQs") didn't account for an extra
instance of that field in the older kernel, resulting in this:

drivers/vhost/scsi.c: In function ‘vhost_scsi_handle_vq’:
drivers/vhost/scsi.c:1038:14: error: ‘struct vhost_dev’ has no member named ‘acked_features’
   if (vs->dev.acked_features & VIRTIO_SCSI_F_T10_PI) {
              ^

Point it at the new location in the vq instead of in the dev.

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>